footer icons hover animation + fix
acm-ucr/h4b-website pull request #131
Opened 2024-08-01 00:39 UTC by xwRongx

![image](https://github.com/user-attachments/assets/ee6e8bed-cf4f-4d59-9c35-2532f3e7cb26)

2024-08-01 01:30 UTC, seanquiambao requested changes

2024-08-01 01:30 UTC, seanquiambao commented on src/components/Footer.jsx
> +    <div className="flex shadow-[0_-2px_3px_0px_rgba(0,0,0,0.1)] items-center p-4 bg-biscuits-peach justify-between text-biscuits-purple-200 font-omc text-2xl md:text-3xl text-center">
you can use tailwind's default drop shadow instead.

2024-08-01 01:30 UTC, seanquiambao commented on src/components/Footer.jsx
> +          <Link className="hover:-translate-y-1" key={index} href={social.link}>
add a transition to the hover

2024-08-02 08:32 UTC, xwRongx commented
![image](https://github.com/user-attachments/assets/b877cff8-c94c-41e8-b700-347dd39a7451)
With the default drop shadow, the footer shadow is different from the header shadow. Is it ok that they don't match?

2024-08-02 17:05 UTC, seanquiambao commented
that should be fine

2024-08-02 17:06 UTC, seanquiambao approved these changes

2024-08-02 17:06 UTC, merged