gallery main page animation
acm-ucr/h4b-website pull request #155
Opened 2024-08-06 09:02 UTC by xwRongx

![image](https://github.com/user-attachments/assets/18a94c2c-954b-4856-bcfc-5a830b530279)
Tried to use different animations but let me know if it's too busy!

2024-08-06 21:04 UTC, seanquiambao commented
wait is that screenshot mid-animation or was the component misaligned on your end?

2024-08-06 21:22 UTC, xwRongx commented
> wait is that screenshot mid-animation or was the component misaligned on your end?

![image](https://github.com/user-attachments/assets/8504f7ab-db1d-462d-85ec-90eb63a5c627)
it was just a badly positioned screenshot lol, it looks centered on my end

2024-08-06 21:23 UTC, seanquiambao commented
oh okii sounds good haha

2024-08-06 22:04 UTC, qhgill requested changes
looks good so far! try experimenting with ref placement so animations play when the viewer scrolls instead of all of them playing at once.

2024-08-06 22:04 UTC, qhgill commented on src/app/gallery/page.js
> +      <div className={`${inView && "animate-flip-up animate-once"} mb-14`}>
you may want to add another ref for this section as the user won't see the animation

2024-08-16 03:58 UTC, seanquiambao approved these changes

2024-08-16 04:01 UTC, merged