Navbar added
acm-ucr/h4b-website pull request #18
Opened 2024-06-28 19:12 UTC by Fuyuki325

Desktop:
![image](https://github.com/acm-ucr/h4b-website/assets/120443522/438b2bc5-4aee-46df-9fb7-09082770a9c4)

Mobile:
![image](https://github.com/acm-ucr/h4b-website/assets/120443522/2bf4127e-1de0-4291-9569-aaa42de0e25b)

2024-06-28 19:14 UTC, Fuyuki325 commented
wait i change font

2024-07-01 22:24 UTC, seanquiambao requested changes
made some changes, but after those comments and using guarjada font this should be good to go!

2024-07-01 22:24 UTC, seanquiambao commented on src/components/Navigation.jsx
> +];
create a data directory and put this in `Navigation.js` file.

2024-07-01 22:24 UTC, seanquiambao commented on src/components/Navigation.jsx
> +          {items.map((item, index) => (
![image](https://github.com/acm-ucr/h4b-website/assets/91030482/770ec1f5-e7ad-47d6-a665-2115184d16b3)
on mobile view, maybe make the text a little bigger.

2024-07-01 23:14 UTC, Fuyuki325 commented
![image](https://github.com/acm-ucr/h4b-website/assets/120443522/1601f515-6db7-4ddb-817c-7b7d18922830)
added gurajada and made text bigger

2024-07-02 05:01 UTC, seanquiambao approved these changes

2024-07-02 17:02 UTC, merged