Updating shadow for mobile on involve page
acm-ucr/h4b-website pull request #196
Opened 2024-08-16 22:56 UTC by ALE00111

![image](https://github.com/user-attachments/assets/2e476652-22b0-4200-9ea5-a28480c02de2)

2024-08-19 00:27 UTC, seanquiambao requested changes
also check the tailwind.config file.

textShadow "sm" is formatted as 0 1px 2px ...(etc etc..)
the first two numbers are the offset shadows.
the second one is the "blurriness" of the shadow (should be set to 0).

2024-08-19 00:27 UTC, seanquiambao commented on src/components/Title.jsx
> +          className={`md:text-shadow [text-shadow:_-3px_4px_0px_var(--tw-shadow-color)]  ${darkColor} font-omc text-5xl md:text-8xl mb-2 drop-shadow left-1 bottom-0.5 ${lightColor} text-center`}
```suggestion
          className={`md:text-shadow text-shadow-sm ${darkColor} font-omc text-5xl md:text-8xl mb-2 drop-shadow left-1 bottom-0.5 ${lightColor} text-center`}
```

2024-08-20 20:00 UTC, seanquiambao requested changes
![image](https://github.com/user-attachments/assets/d1ce3bda-e111-4184-847c-c41210b3b0af)


title shadow should not be blurry. check comment above

2024-08-21 18:56 UTC, ALE00111 commented
Oh sorry I didn't understand the first comment fully. I think that's how it should be after changing the config file.

2024-08-21 22:55 UTC, seanquiambao requested changes

2024-08-21 22:55 UTC, seanquiambao commented on tailwind.config.js
> +        sm: "0 3px 0px var(--tw-shadow-color)",
```suggestion
        sm: "-3px 3px 0px var(--tw-shadow-color)",
```

2024-08-23 01:18 UTC, seanquiambao approved these changes

2024-08-23 01:20 UTC, merged