added info to support page
acm-ucr/h4b-website pull request #74
Opened 2024-07-15 09:07 UTC by xwRongx

![image](https://github.com/user-attachments/assets/ef64946e-50c5-4728-b5f4-5d37a84f0438)

2024-07-15 21:31 UTC, qhgill requested changes
looks good other than spacing problem with social links, just make sure to pull from dev beforehand to get changes.

2024-07-15 21:31 UTC, qhgill commented on src/components/support/Support.jsx
> +        <div className="flex justify-evenly translate-y-5">
the socials overlap with the footer, add padding to fix spacing

2024-07-16 20:35 UTC, xwRongx commented
![image](https://github.com/user-attachments/assets/9793fc43-ecf3-4514-8b98-22fbba950ea6)

2024-07-16 20:53 UTC, qhgill approved these changes

2024-07-16 20:53 UTC, merged