implement support page
acm-ucr/h4b-website pull request #78
Opened 2024-07-17 23:03 UTC by xwRongx

![image](https://github.com/user-attachments/assets/4a8b7fc6-93bf-4e0c-9221-61f7210ae15e)

2024-07-17 23:36 UTC, qhgill requested changes, later dismissed
add background color to the support page to match Figma, otherwise looks good!

2024-07-18 04:14 UTC, qhgill commented on src/components/support/Support.jsx
>        <div className="text-center text-biscuits-brown-200 font-shrikhand text-5xl">
replace this with subtitle component

2024-07-18 04:14 UTC, qhgill commented on src/components/support/Support.jsx
> +        <Image src={standing} alt="standing" />
move mascot closer to the text

2024-07-19 04:03 UTC, xwRongx commented
![image](https://github.com/user-attachments/assets/4eae4cca-a853-4d91-8a96-4e155f5c5594)

2024-07-19 08:57 UTC, seanquiambao approved these changes

2024-07-19 08:58 UTC, merged